Repository Russel-FS/ng-UrbanNest, pull requests merged in 2025-02, with the labels that each got.

#5 Test a
  src/app/app.routes.ts
  src/app/presentation/pages/admin/admin.routes.ts
  src/app/presentation/pages/admin/reports/reports.component.html
  src/app/presentation/pages/admin/reports/reports.component.scss
  src/app/presentation/pages/admin/reports/reports.component.ts
  src/app/presentation/pages/admin/system-config/system-config.component.html
  src/app/presentation/pages/admin/system-config/system-config.component.scss
  src/app/presentation/pages/admin/system-config/system-config.component.ts
  src/app/presentation/pages/admin/user-management/user-management.component.html
  src/app/presentation/pages/admin/user-management/user-management.component.scss
  src/app/presentation/pages/admin/user-management/user-management.component.ts
  src/app/presentation/pages/agent/agent.routes.ts
  src/app/presentation/pages/agent/property-review/property-review.component.html
  src/app/presentation/pages/agent/property-review/property-review.component.scss
  src/app/presentation/pages/agent/property-review/property-review.component.ts
  src/app/presentation/pages/agent/review-history/review-history.component.html
  src/app/presentation/pages/agent/review-history/review-history.component.scss
  src/app/presentation/pages/agent/review-history/review-history.component.ts
  src/app/presentation/pages/properties/property-form/property-form.component.html
  src/app/presentation/pages/properties/property-form/property-form.component.scss
  src/app/presentation/pages/properties/property-form/property-form.component.ts
  src/app/presentation/pages/properties/property-list/property-list.component.html
  src/app/presentation/pages/properties/property-list/property-list.component.scss
  src/app/presentation/pages/properties/property-list/property-list.component.ts
  src/app/presentation/shared/components/notification/notification.component.html
  src/app/presentation/shared/components/notification/notification.component.scss
  src/app/presentation/shared/components/notification/notification.component.ts
  src/app/presentation/shared/components/property-card/property-card.component.html
  src/app/presentation/shared/components/property-card/property-card.component.scss
  src/app/presentation/shared/components/property-card/property-card.component.ts
  src/app/presentation/shared/components/status-badge/status-badge.component.ts
Labels: enhancement

#6 Test a
  src/app/app.routes.ts
  src/app/presentation/pages/properties/property-form/property-form.component.html
  src/app/presentation/pages/properties/property-form/property-form.component.ts
  src/app/presentation/pages/properties/publish-property/account-setup-form/account-setup-form.component.css
  src/app/presentation/pages/properties/publish-property/account-setup-form/account-setup-form.component.html
  src/app/presentation/pages/properties/publish-property/account-setup-form/account-setup-form.component.spec.ts
  src/app/presentation/pages/properties/publish-property/account-setup-form/account-setup-form.component.ts
  src/app/presentation/pages/properties/publish-property/extras/extras.component.css
  src/app/presentation/pages/properties/publish-property/extras/extras.component.html
  src/app/presentation/pages/properties/publish-property/extras/extras.component.spec.ts
  src/app/presentation/pages/properties/publish-property/extras/extras.component.ts
  src/app/presentation/pages/properties/publish-property/main/main.component.css
  src/app/presentation/pages/properties/publish-property/main/main.component.html
  src/app/presentation/pages/properties/publish-property/main/main.component.spec.ts
  src/app/presentation/pages/properties/publish-property/main/main.component.ts
  src/app/presentation/pages/properties/publish-property/multimedia/multimedia.component.css
  src/app/presentation/pages/properties/publish-property/multimedia/multimedia.component.html
  src/app/presentation/pages/properties/publish-property/multimedia/multimedia.component.spec.ts
  src/app/presentation/pages/properties/publish-property/multimedia/multimedia.component.ts
  src/app/presentation/pages/properties/publish-property/publish/publish.component.css
  src/app/presentation/pages/properties/publish-property/publish/publish.component.html
  src/app/presentation/pages/properties/publish-property/publish/publish.component.spec.ts
  src/app/presentation/pages/properties/publish-property/publish/publish.component.ts
  src/app/presentation/shared/components/notification/notification.component.html
  src/app/presentation/shared/components/notification/notification.component.ts
  src/app/presentation/shared/components/progress-tracker/progress-tracker.component.css
  src/app/presentation/shared/components/progress-tracker/progress-tracker.component.html
  src/app/presentation/shared/components/progress-tracker/progress-tracker.component.spec.ts
  src/app/presentation/shared/components/progress-tracker/progress-tracker.component.ts
  src/app/presentation/shared/components/property-card/property-card.component.scss
Labels: enhancement

#7 Desing b
  create-structure.sh
  src/app/core/services/progress-tracker-service.service.spec.ts
  src/app/core/services/progress-tracker-service.service.ts
  src/app/core/services/progress-vertical-service.service.spec.ts
  src/app/core/services/progress-vertical-service.service.ts
  src/app/presentation/layout/layout.component.html
  src/app/presentation/pages/properties/publish-property/main/main.component.html
  src/app/presentation/pages/properties/publish-property/main/main.component.ts
  src/app/presentation/pages/properties/publish-property/property-details/characteristics/characteristics.component.css
  src/app/presentation/pages/properties/publish-property/property-details/characteristics/characteristics.component.html
  src/app/presentation/pages/properties/publish-property/property-details/characteristics/characteristics.component.spec.ts
  src/app/presentation/pages/properties/publish-property/property-details/characteristics/characteristics.component.ts
  src/app/presentation/pages/properties/publish-property/property-details/location/location.component.css
  src/app/presentation/pages/properties/publish-property/property-details/location/location.component.html
  src/app/presentation/pages/properties/publish-property/property-details/location/location.component.spec.ts
  src/app/presentation/pages/properties/publish-property/property-details/location/location.component.ts
  src/app/presentation/pages/properties/publish-property/property-details/property-details.component.css
  src/app/presentation/pages/properties/publish-property/property-details/property-details.component.html
  src/app/presentation/pages/properties/publish-property/property-details/property-details.component.spec.ts
  src/app/presentation/pages/properties/publish-property/property-details/property-details.component.ts
  src/app/presentation/pages/properties/publish-property/property-details/type-property/type-property.component.css
  src/app/presentation/pages/properties/publish-property/property-details/type-property/type-property.component.html
  src/app/presentation/pages/properties/publish-property/property-details/type-property/type-property.component.spec.ts
  src/app/presentation/pages/properties/publish-property/property-details/type-property/type-property.component.ts
  src/app/presentation/shared/components/progress-tracker/progress-tracker.component.html
  src/app/presentation/shared/components/progress-vertical/progress-vertical.component.css
  src/app/presentation/shared/components/progress-vertical/progress-vertical.component.html
  src/app/presentation/shared/components/progress-vertical/progress-vertical.component.spec.ts
  src/app/presentation/shared/components/progress-vertical/progress-vertical.component.ts
Labels: enhancement

#8 Desing b
  src/app/presentation/shared/components/progress-vertical/progress-vertical.component.html
Labels: good first issue

#12 Desing b
  src/app/core/services/geocoding.service.ts
  src/app/presentation/pages/properties/publish-property/property-details/location/location.component.html
  src/app/presentation/pages/properties/publish-property/property-details/location/location.component.ts
Labels: enhancement

#15 Feature/property characteristics
  src/app/presentation/pages/properties/publish-property/property-details/characteristics/characteristics.component.html
  src/app/presentation/pages/properties/publish-property/property-details/characteristics/characteristics.component.ts
  src/app/presentation/pages/properties/publish-property/property-details/property-details.component.ts
Labels: good first issue

#17 Feature/property characteristics
  src/.prettierrc
  src/app/core/services/geocoding.service.ts
  src/app/core/services/progress-tracker-service.service.ts
  src/app/core/services/progress-vertical-service.service.ts
  src/app/presentation/layout/layout.component.html
  src/app/presentation/layout/layout.component.ts
  src/app/presentation/pages/activity-messages/activity-messages.component.html
  src/app/presentation/pages/activity-messages/contacts/contacts.component.html
  src/app/presentation/pages/activity-messages/contacts/contacts.component.ts
  src/app/presentation/pages/activity-messages/discarded/discarded.component.html
  src/app/presentation/pages/activity-messages/discarded/discarded.component.ts
  src/app/presentation/pages/activity-messages/favorites/favorites.component.html
  src/app/presentation/pages/activity-messages/history/history.component.html
  src/app/presentation/pages/activity-messages/searches/searches.component.html
  src/app/presentation/pages/admin/admin.routes.ts
  src/app/presentation/pages/admin/reports/reports.component.html
  src/app/presentation/pages/admin/reports/reports.component.ts
  src/app/presentation/pages/admin/system-config/system-config.component.html
  src/app/presentation/pages/admin/system-config/system-config.component.ts
  src/app/presentation/pages/admin/user-management/user-management.component.html
  src/app/presentation/pages/admin/user-management/user-management.component.ts
  src/app/presentation/pages/agent/agent.routes.ts
  src/app/presentation/pages/agent/property-review/property-review.component.html
  src/app/presentation/pages/agent/property-review/property-review.component.ts
  src/app/presentation/pages/agent/review-history/review-history.component.html
  src/app/presentation/pages/auth/login/login.component.html
  src/app/presentation/pages/auth/login/login.component.ts
  src/app/presentation/pages/auth/register/register.component.html
  src/app/presentation/pages/auth/register/register.component.ts
  src/app/presentation/pages/home/home.component.html
  src/app/presentation/pages/home/home.component.ts
  src/app/presentation/pages/properties/property-list/property-list.component.html
  src/app/presentation/pages/properties/property-list/property-list.component.ts
  src/app/presentation/pages/properties/publish-property/account-setup-form/account-setup-form.component.html
  src/app/presentation/pages/properties/publish-property/main/main.component.html
  src/app/presentation/pages/properties/publish-property/main/main.component.ts
  src/app/presentation/pages/properties/publish-property/multimedia/multimedia.component.html
  src/app/presentation/pages/properties/publish-property/multimedia/multimedia.component.ts
  src/app/presentation/pages/properties/publish-property/property-details/characteristics/characteristics.component.html
  src/app/presentation/pages/properties/publish-property/property-details/location/location.component.html
  src/app/presentation/pages/properties/publish-property/property-details/location/location.component.ts
  src/app/presentation/pages/properties/publish-property/property-details/property-details.component.html
  src/app/presentation/pages/properties/publish-property/property-details/property-details.component.ts
  src/app/presentation/pages/properties/publish-property/property-details/type-property/type-property.component.html
  src/app/presentation/shared/components/progress-tracker/progress-tracker.component.html
  src/app/presentation/shared/components/progress-tracker/progress-tracker.component.ts
  src/index.html
Labels: documentation, enhancement
